# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@3
  displayName: 'Azure PowerShell script: FilePath'
  inputs:
    azureSubscription: 'CSE 2 (5355e294-a200-4df6-86f4-aaaceaf646ca)'
    ScriptPath: 'Deploy-AzTemplate.ps1'
    ScriptArguments: '-Location ''westus2' -TemplateFile 'azuredeploy.jso n' -TemplateParametersFile 'azuredeploy.parameters.json' -StorageAccountName '' -ArtifactStagingDirectory '.' -StorageCo ntainerName 'azurepolicypipeline-storageaccount' -UploadArtifacts'
    azurePowerShellVersion: LatestVersion